# Generated by Django 4.1.4 on 2022-12-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_Of_Content', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Place', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('OnGoing_Contests', models.BooleanField(blank=True, default=None, null=True)),
                ('Start_Time', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Start_Date', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Remaining_Time', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Entry_Price', models.IntegerField(blank=True, default=None, null=True)),
                ('Price_Pool', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
    ]
