# Generated by Django 4.1.4 on 2023-01-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_is_verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
