# Generated by Django 4.1.4 on 2022-12-27 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contests',
            old_name='Name_Of_Content',
            new_name='Name_Of_Contest',
        ),
    ]
