# Generated by Django 4.1.4 on 2022-12-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_name_of_content_contests_name_of_contest'),
    ]

    operations = [
        migrations.AddField(
            model_name='contests',
            name='Contest_Duration',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contests',
            name='Days_Remaining_For_The_Contest_To_Start',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contests',
            name='Days_Remaining_To_Register',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
