# Generated by Django 4.1.4 on 2023-01-20 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_email_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='contests',
            name='Contest_Type',
            field=models.CharField(blank=True, default=None, max_length=225, null=True),
        ),
    ]
