# Generated by Django 4.1.4 on 2022-12-30 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_contests_contest_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contests',
            name='OnGoing_Contests',
        ),
    ]
