# Generated by Django 4.1.4 on 2023-01-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_contests_contest_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contests',
            name='Contest_Mode',
            field=models.CharField(blank=True, default=None, max_length=225, null=True),
        ),
    ]
