# Generated by Django 4.1.4 on 2022-12-31 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_contests_ongoing_contests'),
    ]

    operations = [
        migrations.AddField(
            model_name='contests',
            name='OnGoing',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='contests',
            name='Contest_Duration',
            field=models.CharField(blank=True, default=None, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='contests',
            name='Days_Remaining_For_The_Contest_To_Start',
            field=models.CharField(blank=True, default=None, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='contests',
            name='Days_Remaining_To_Register',
            field=models.CharField(blank=True, default=None, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='contests',
            name='Name_Of_Contest',
            field=models.CharField(blank=True, default=None, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='contests',
            name='Place',
            field=models.CharField(blank=True, default=None, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='contests',
            name='Remaining_Time',
            field=models.CharField(blank=True, default=None, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='contests',
            name='Start_Date',
            field=models.CharField(blank=True, default=None, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='contests',
            name='Start_Time',
            field=models.CharField(blank=True, default=None, max_length=225, null=True),
        ),
    ]
