# Generated by Django 4.1.4 on 2022-12-31 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_contests_ongoing_alter_contests_contest_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contests',
            name='Name_Of_Website',
            field=models.CharField(blank=True, default=None, max_length=225, null=True),
        ),
    ]
