# Generated by Django 4.1.4 on 2022-12-31 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_contests_name_of_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contests',
            name='Place',
            field=models.CharField(blank=True, default='Online', max_length=225, null=True),
        ),
    ]
