# Generated by Django 4.1.4 on 2023-01-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_contests_contest_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contests',
            name='Entry_Price',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='contests',
            name='Price_Pool',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
