# Generated by Django 4.1.4 on 2023-01-20 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_contests_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contests',
            old_name='id',
            new_name='new_id',
        ),
    ]
