# Generated by Django 4.1.4 on 2023-01-20 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_id_contests_new_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contests',
            old_name='new_id',
            new_name='id',
        ),
    ]
