# Generated by Django 4.1.4 on 2023-01-20 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_calender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contests',
            name='Added_To_Calender',
        ),
        migrations.AddField(
            model_name='calender',
            name='contest_link',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='calender',
            name='contest_name',
            field=models.CharField(blank=True, default=None, max_length=225, null=True),
        ),
    ]
