# Generated by Django 4.1.4 on 2023-01-20 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_contests_added_to_calender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calender',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
