# Generated by Django 4.1.4 on 2023-01-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_calender_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='calender',
            name='contest_start_time',
            field=models.CharField(blank=True, default=None, max_length=225, null=True),
        ),
    ]
